 # -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from os import path
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QInputDialog, QTextBrowser
from PyQt5.QtWidgets import QMessageBox
import cv2
import os
import glob
from main_enhancement import*
from AES import convert_hex_text, decrypt, encrypt, state_to_text

from numpy.lib.type_check import imag

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1066, 835)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        #encrypt
        self.encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.encrypt.setGeometry(QtCore.QRect(110, 710, 231, 71))
        self.encrypt.setObjectName("Encrypt")
        

        #Decrypt
        self.decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.decrypt.setGeometry(QtCore.QRect(510, 700, 231, 71))
        self.decrypt.setObjectName("Decrypt")\
        
        #plain text encrypt
        self.plaintext = QtWidgets.QLineEdit(self.centralwidget)
        self.plaintext.setGeometry(QtCore.QRect(40, 520, 371, 51))
        self.plaintext.setObjectName("lineEdit")
        #self.plaintext.returnPressed.connect(self.encrypt_1)

        #cirpher text decrypt

        self.cipherdecry = QtWidgets.QTextBrowser(self.centralwidget)
        self.cipherdecry.setGeometry(QtCore.QRect(510, 520, 361, 51))
        self.cipherdecry.setObjectName("cipher text decrypt")

        #self.ciphertext.returnPressed.connect(self.append_text)

        self.encry_plain = QtWidgets.QLabel(self.centralwidget)
        self.encry_plain.setGeometry(QtCore.QRect(40, 500, 101, 17))
        self.encry_plain.setObjectName("Plaintext")
        
        self.key = QtWidgets.QLabel(self.centralwidget)
        self.key.setGeometry(QtCore.QRect(650, 270, 67, 17))
        self.key.setObjectName("key")
        
        #button Key
        self.buttonkey = QtWidgets.QPushButton(self.centralwidget)
        self.buttonkey.setGeometry(QtCore.QRect(780, 150, 161, 41))
        self.buttonkey.setObjectName("Button Key")

        self.encry_cipher = QtWidgets.QLabel(self.centralwidget)
        self.encry_cipher.setGeometry(QtCore.QRect(40, 600, 121, 17))
        self.encry_cipher.setObjectName("Ciphertext")

        self.decry_plain = QtWidgets.QLabel(self.centralwidget)
        self.decry_plain.setGeometry(QtCore.QRect(510, 600, 121, 17))
        self.decry_plain.setObjectName("label_5")
        
        self.decry_cipher = QtWidgets.QLabel(self.centralwidget)
        self.decry_cipher.setGeometry(QtCore.QRect(510, 500, 101, 17))
        self.decry_cipher.setObjectName("label_6")
        
        #view origin image
        self.origin_image = QtWidgets.QGraphicsView(self.centralwidget)
        self.origin_image.setGeometry(QtCore.QRect(10, 30, 311, 421))
        self.origin_image.setObjectName("originImage")
        
        self.scene_origin = QtWidgets.QGraphicsScene()
        self.scene_result = QtWidgets.QGraphicsScene()

        self.origin = QtWidgets.QLabel(self.centralwidget)
        self.origin.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.origin.setObjectName("label_7")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(330, 10, 71, 20))
        self.result.setObjectName("label_8")

        #choose Image
        self.chooseImage1 = QtWidgets.QPushButton(self.centralwidget)
        self.chooseImage1.setGeometry(QtCore.QRect(780, 90, 161, 41))
        self.chooseImage1.setObjectName("pushButton_4")
        self.chooseImage1.clicked.connect(self.saveImg_origin1)

        #view result image
        self.result_image = QtWidgets.QGraphicsView(self.centralwidget)
        self.result_image.setGeometry(QtCore.QRect(330, 30, 311, 421))
        self.result_image.setObjectName("resultImage")

        self.encrypt_cipher = QtWidgets.QTextBrowser(self.centralwidget)
        self.encrypt_cipher.setGeometry(QtCore.QRect(40, 620, 371, 51))
        self.encrypt_cipher.setObjectName("textBrowser")
        self.encrypt_cipher.setAcceptRichText(True)
        self.encrypt_cipher.setOpenExternalLinks(True)

        self.decrypt_plain = QtWidgets.QTextBrowser(self.centralwidget)
        self.decrypt_plain.setGeometry(QtCore.QRect(510, 620, 361, 51))
        self.decrypt_plain.setObjectName("textBrowser_2")
       
        self.show_key = QtWidgets.QTextBrowser(self.centralwidget)
        self.show_key.setGeometry(QtCore.QRect(650, 290, 411, 51))
        self.show_key.setObjectName("Key")
        #self.show_key = QTextBrowser()
        self.show_key.setAcceptRichText(True)
        self.show_key.setOpenExternalLinks(True)

        self.image = QtWidgets.QWidgetAction(MainWindow)
        self.image.setObjectName("Image")
        
        #status
        self.status1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.status1.setGeometry(QtCore.QRect(900, 700, 151, 71))
        self.status1.setObjectName("Status")

        self.label_stt = QtWidgets.QLabel(self.centralwidget)
        self.label_stt.setGeometry(QtCore.QRect(900, 680, 67, 17))
        self.label_stt.setObjectName("label_4")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1066, 22))
        self.menubar.setObjectName("menubar")
        self.chooseImage = QtWidgets.QMenu(self.menubar)
        self.chooseImage.setObjectName("menumenu")

        self.chooseImage.addAction(self.image)

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiongdf = QtWidgets.QAction(MainWindow)
        self.actiongdf.setObjectName("actiongdf")
        self.chooseImage.addSeparator()
        self.chooseImage.addSeparator()
        self.menubar.addAction(self.chooseImage.menuAction())

        #button encrypt
        self.encrypt.clicked.connect(self.encrypt_1)
        self.buttonkey.clicked.connect(self.load_result)
        self.decrypt.clicked.connect(self.decrypt_1)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.key128bits = None
        self.pathImage = None
        self.ciphertextTrue = None
        self.plain_regres = None
        self.plain_result = None

    def saveImg_origin1(self):
        dirOrigin_folder = QFileDialog.getOpenFileName(directory='/home')
        #print(dirOrigin_folder)

        self.dirOriginCam1 = dirOrigin_folder[0]
        pathimage = os.path.basename(dirOrigin_folder[0])
        print(pathimage)
        self.pathImage = str(pathimage)
        self.load_image(self.dirOriginCam1)
        return pathimage

    #show image & key
    '''def load_origin(self):
        self.load_image(self.)'''
    def load_result(self):
        self.load_result_image('/home/ttc21/Documents/ltmm/FingerprintFeatureExtraction/enhanced/Minutiae.bmp')
        self.key128bits = main(self.pathImage)
        self.show_key_1(self.key128bits)
    #show Key
    def show_key_1(self, key):
        self.show_key.clear()
        self.show_key.append(str(key))
    #encrypt
     

    def encrypt_1(self):
        plaintext = self.plaintext.text()
        print(plaintext)
        self.plain_regres = plaintext
        print(self.key128bits)
        encry = encrypt(str(plaintext), self.key128bits, nB = 4, nR = 10)
        self.ciphertextTrue = encry
        self.encrypt_cipher.clear()
        self.encrypt_cipher.append(str(encry))

    def decrypt_1(self):
        self.cipherdecry.clear()
        self.cipherdecry.append(str(self.ciphertextTrue))
        decry = decrypt(str(self.ciphertextTrue), self.key128bits, nB = 4, nR = 10)
        self.plain_result = decry
        self.decrypt_plain.clear()
        self.decrypt_plain.append(str(decry))
        self.status1.clear()
        if self.plain_regres ==  self.plain_result:
            self.status1.append("\nOK")
        else:
            self.status1.append("\nERROR")
    #from PIL import Image
    #import Image
    def load_image(self, path):
        img = cv2.imread(path, cv2.IMREAD_UNCHANGED)
        img = cv2.resize(img, (600,800)) 
        #img = QtGui.QImage(img.data, img.shape[1], img.shape[0], img.shape[1], QtGui.QImage.Fo)
        pixmap = QtGui.QPixmap(path)
        item = QtWidgets.QGraphicsPixmapItem(pixmap)
        self.scene_origin.clear()
        self.scene_origin.addItem(item)
        
        self.origin_image.setScene(self.scene_origin)
    
    def load_result_image(self, path):
        img = cv2.imread(path, cv2.IMREAD_UNCHANGED)
        img = cv2.resize(img, (300,400)) 
        img = QtGui.QImage(img.data, img.shape[1], img.shape[0], img.shape[1], QtGui.QImage.Format_Grayscale8)
        pixmap = QtGui.QPixmap(path)
        item = QtWidgets.QGraphicsPixmapItem(pixmap)
        self.scene_result.clear()
        self.scene_result.addItem(item)
        
        self.result_image.setScene(self.scene_result)    
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.encrypt.setText(_translate("MainWindow", "REGISTRATION (Encrypt)"))
        self.decrypt.setText(_translate("MainWindow", "OPEN (Decrypt)"))
        self.encry_plain.setText(_translate("MainWindow", "PLAIN TEXT"))
        self.key.setText(_translate("MainWindow", "KEY"))
        self.encry_cipher.setText(_translate("MainWindow", "CIPHER TEXT"))
        self.decry_plain.setText(_translate("MainWindow", "PLAIN TEXT"))
        self.decry_cipher.setText(_translate("MainWindow", "CIPHER TEXT"))
        self.origin.setText(_translate("MainWindow", "ORIGIN"))
        self.result.setText(_translate("MainWindow", "RESULT"))
        self.buttonkey.setText(_translate("MainWindow", "KEY "))
        self.chooseImage.setTitle(_translate("MainWindow", "image"))
        self.actiongdf.setText(_translate("MainWindow", "gdf"))
        self.chooseImage1.setText(_translate("MainWindow", "Choose Image"))
        self.label_stt.setText(_translate("MainWindow", "STATUS"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
